version: 2.1

commands:
  install-cargo:
    steps:
      - run:
          name: Updating apt-get
          command: 'sudo apt-get update -y'
      - run:
          name: Installing Cargo
          command: 'sudo apt-get install -y cargo'
      - run: 
          name: Pulling down rustup Install Script
          command: `curl --proto '=http\' --tlsv1.2 -sSf https://sh.rustup.rs  > rust.sh`
      - run: 
          name: Changing permissions on rustup script
          command: 'chmod +x ./rust.sh'
      - run:
          name: Installing rustup
          command: './rust.sh --yes'
      - run: 
          name: Installing Nightly
          command: 'rustup install nightly'
          
  install-rust:
    steps:
      - run: 
          name: DEBUG getting file path
          command: 'pwd'
      - run:
          name: DEBUG getting file path 2
          command: 'ls -a'
      - run:
          name: Installing Rust Nightly Channel
          command: 'cargo +nightly install --path rust/RestAPI'

  build:
    steps:
    - checkout 
    - install-cargo
    - install-rust


executors:
  machine-executor:
    machine:
      image: ubuntu-2004:202010-01

jobs:
  build-with-linux:
    executor: machine-executor
    steps:
      - build

workflows:
  build-with-machine:
    jobs:
      - build-with-linux