version: 2.1

commands:
  install-cargo:
    steps:
      - run:
          name: Installing Cargo
          command: 'curl https://sh.rustup.rs -sSf | sh'

  install-rust:
    steps:
      - run: 
          name: Installing Rust Depenedencies
          command: 'cargo install --path ../rust/RestAPI'

  build:
    steps:
    - checkout 
    - install-cargo
    - install-rust


executors:
  machine-executor:
    machine:
      image: ubuntu-2004:202010-01

jobs:
  build-with-linux:
    executor: machine-executor
    steps:
      - build

workflows:
  build-with-machine:
    jobs:
      - build-with-linux