[package]
name = "Load-Test-Api"
version = "0.1.0"
authors = ["msilveus1 <msilveus@wisc.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.4"
rocket_codegen = "0.4.4"